In [1]:
import torch
from torchmetrics.retrieval import RetrievalHitRate

In [20]:
hit_rate = RetrievalHitRate(top_k=3)

pos_logits = torch.tensor([[0.1], [0.4]])
neg_logits = torch.tensor([[0.2, 0.3, 0.4], [0.3, 0.2, 0.1]])
logits = torch.cat([pos_logits, neg_logits], dim=1)
target = torch.cat([torch.ones_like(pos_logits), torch.zeros_like(neg_logits)], dim=1).bool()
batch_size, num_samples = logits.size()
indexes = torch.arange(batch_size).reshape(batch_size, 1).expand(batch_size, num_samples)

print(logits)
print(target)
print(indexes)

hit_rate(logits, target, indexes)

tensor([[0.1000, 0.2000, 0.3000, 0.4000],
        [0.4000, 0.3000, 0.2000, 0.1000]])
tensor([[ True, False, False, False],
        [ True, False, False, False]])
tensor([[0, 0, 0, 0],
        [1, 1, 1, 1]])


tensor(0.5000)