# Amazon Reviews 2023

[Amazon Reviews 2023](https://github.com/hyp1231/AmazonReviews2023)


In [1]:
import pathlib
import sys

sys.path.append("..")

from data.dataset import AmazonReviewsDataModule

In [2]:
save_dir = pathlib.Path("../data/data")
if not save_dir.exists():
    save_dir.mkdir(parents=True)

datamodule = AmazonReviewsDataModule(save_dir, batch_size=32, num_workers=1, max_seq_len=50)

In [3]:
datamodule.prepare_data()

In [4]:
datamodule.setup(stage="fit")

In [5]:
train_dataloader = datamodule.train_dataloader()
user_index, item_history, pos_item_index, neg_item_indexes = next(iter(train_dataloader))

In [6]:
user_index.size(), user_index

(torch.Size([32]),
 tensor([170313,  34660, 234243, 245991, 180018,  49481,  50468, 105880, 130118,
         241866, 126983, 310465, 236558,  38555, 324749, 272033, 232854, 188085,
         258581,  28112,   4437, 139541, 112355, 288430,  29657, 298257, 233793,
          55441, 244881,  49188, 211247, 208047]))

In [7]:
item_history.size(), item_history

(torch.Size([32, 50]),
 tensor([[    0,     0,     0,  ..., 81180, 81230, 78060],
         [    0,     0,     0,  ..., 33608, 45980, 65217],
         [    0,     0,     0,  ..., 51895, 47340, 45663],
         ...,
         [    0,     0,     0,  ...,     0,     0, 30960],
         [    0,     0,     0,  ..., 25333, 30215, 32125],
         [    0,     0,     0,  ..., 24588, 25259, 11664]]))

In [8]:
pos_item_index.size(), pos_item_index

(torch.Size([32, 1]),
 tensor([[82332],
         [64459],
         [77277],
         [  534],
         [56044],
         [27130],
         [48240],
         [34858],
         [31103],
         [42465],
         [52537],
         [48244],
         [37864],
         [67463],
         [26381],
         [48412],
         [49332],
         [30771],
         [23415],
         [32091],
         [21866],
         [29889],
         [65065],
         [65215],
         [ 2913],
         [65198],
         [ 4762],
         [66527],
         [42824],
         [31285],
         [50063],
         [ 2666]]))

In [9]:
neg_item_indexes.size(), neg_item_indexes

(torch.Size([32, 5]),
 tensor([[50314, 14280, 42116, 49771, 51858],
         [19387, 79439, 41085, 47676, 36268],
         [34606, 63928, 69459, 71334, 48222],
         [21964, 73734, 58313, 72845,  8105],
         [27152,  9384, 29102, 14920, 46210],
         [43482, 56296, 69703,  6161,  3891],
         [48813, 44161, 25286, 38134, 49781],
         [38780, 35000, 25593, 17367,  6887],
         [49173, 13792, 72754, 63512,   246],
         [17235, 53910,  4025, 60722, 15808],
         [ 9193, 36803, 34118, 72528, 23734],
         [76797,  4093, 80240, 49468, 12822],
         [55264, 12498, 25115,  7925,   525],
         [ 5797, 37722, 66660, 33774, 20282],
         [18481, 46174, 62491, 45904, 50525],
         [13241, 15860, 47811, 39947, 22024],
         [  908, 45420, 44068, 18966, 46519],
         [41257, 62879, 35134, 74137, 55947],
         [76857, 66120, 19556, 12129, 26526],
         [43794, 38313, 51585, 50949, 38808],
         [37723, 36366, 16529, 26254,  4126],
         [78